CREATE SCHEMA IF NOT EXISTS auth;
CREATE USER auth_service WITH PASSWORD 'auth123';
GRANT ALL PRIVILEGES ON SCHEMA auth TO auth_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO auth_service;
